version: '3'
services:
    client:
        image: node:8.10
        working_dir: /client
        command: npm run start
        volumes:
            - ./client:/client
        ports:
            - "3000:3000"
    server:
        image: node:7.7
        working_dir: /server
        command: npm run dev
        volumes:
            - ./server:/server
            - ./server/media:/media
        ports:
            - "7000:7000"
        environment:
            NODE_ENV: ${NODE_ENV}
        depends_on: 
            - rethinkdb
    rethinkdb:
        image: rethinkdb
        working_dir: /database
        command: rethinkdb --bind all
        volumes:
            - ./data:/data
        ports:
            - "28015"
            - "29015"
            - "8080:8080"
                